# This is a fun game to guess a random number in between one and one hundred that is generated by computer
# 3 levels in this game (low, medium, hard)
# In 'low level' yoy get 10 chances for guess the right one
# In 'medium level' yoy get 8 chances for guess the right one
# In 'hard level' yoy get 5 chances for guess the right one
# On every wrong guess system shows you that
# your guess value is higher or smaller than the actual value generated by computer.
# A practical example of binary search

import random
computer = random.randint(1,101)
level = int(input("Select level \n type: 1(for low)\n type: 2(for medium)\n type: 3(for hard)\n"))
chances = 10
if level == 1:
    chances = 10
elif level == 2:
    chances = 8
elif level == 3:
    chances = 5

while chances > 0:
    guess = int(input("Guess a number : "))
    if chances == 1:
        if guess == computer:
            print(f"Congrats! {computer} is the right value")
        else:
            print(f"So sad, you couldn't guess the number. Number was {computer}")
        break
    elif guess > computer:
        chances -= 1
        print(f"your value is greater, still you have {chances} chance")
    elif guess < computer:
        chances -= 1
        print(f"your value is lesser, still you have {chances} chance")
    else:
        print(f"Congrats! {computer} is the right value")
        break






